services:
  postgres:
    container_name: vads-postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/volumes/postgres:/data/db

